import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { twMerge } from "tailwind-merge";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ES Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={twMerge(openSans.className, "bg-slate-400")}>
        <video
          src="/assets/intro.mp4"
          autoPlay
          loop
          muted
          className="absolute w-auto min-w-full min-h-full max-h-none opacity-80 object-cover -z-10"
        />
        {children}
      </body>
    </html>
  );
}
