import { twMerge } from "tailwind-merge";
import { Open_Sans } from "next/font/google";
import type { Metadata } from "next";

import "./globals.css";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ES Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={twMerge(openSans.className, "bg-slate-400")}>
        {children}
      </body>
    </html>
  );
}
